name: OSS Governance

on:
  push:
    branches: [main]
    paths: [.github/labels.yml, .github/workflows/oss-governance-labels.yml]

permissions:
  contents: read
  issues: write

jobs:
  main:
    name: Governance Labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # tag=v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
