name: OSS Governance

on:
  push:
    branches: [main]
    paths: [.github/labels.yml, .github/workflows/oss-governance-labels.yml]

permissions:
  contents: read
  issues: write

jobs:
  main:
    name: Governance Labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # tag=v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
